name: Deploy to Production

on:
  release:
    types: [released]

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VALUE_TO_ENCODE: ${{ secrets.VALUE_TO_ENCODE }}
        run: npm run build

      - name: Deploy to Production
        env:
          VALUE_TO_ENCODE: ${{ secrets.VALUE_TO_ENCODE }}
        run: npm run deploy:prod